### ISSUE TITLE
Color codes mess up output when using `more` or `less`

### ISSUE THREAD

**Issue by vkoskiv** [sjmulder/hxl#1]
I know this is just a little experimental project, but I got to wondering if there would be a way to detect piping out to other programs and disable the color codes. (Without using flags.)

**Comment by sjmulder** [comment]
This could be implemented by using [isatty(STDOUT_FILENO)](http://man.openbsd.org/isatty) and ideally respecting `CLICOLOR` and `CLICOLOR_FORCE`, as [nostt](https://github.com/nostt) does:

> <dl>
>   <dt>CLICOLOR</dt>
>   <dd>When set to 0, color output is disabled.</dd>
>   <dt>CLICOLOR_FORCE</dt>
>   <dd>When set to 1, color output is enabled even output is redirect to a pipe or file.</dd>
> </dl>

The reasons I didn't here are

 - Without colours a whole new optimisation can of worms is opened because the output is now of a fixed size and format and I didn't want to bother.
 - It's perfectly valid to pipe coloured output (less accepts it with `-R`).
 - The "cat -v considered harmful" argument: rather than implement this sort of logic everywhere one could use another program in the pipeline.

But if you're so inclined I'll happily accept a pull request for the logic above.
